"""Emit LaTeX macros (VARIABLES ONLY — no prose) from results/analysis.json.

This is the single source of truth for every number in paper/paper.tex. The paper
\\input{}s paper/macros.tex and references each value by name (e.g. \\resDeltaDroidDetect),
so no number is ever hand-typed into the prose. Edit prose in paper/paper.tex; edit
numbers nowhere (re-run this script).

Macro names are letters-only (LaTeX requirement): \\res<CamelCaseName>.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src import config as C

PAPER = C.ROOT / "paper"
PAPER.mkdir(exist_ok=True)
DET = list(C.DETECTOR_FAMILY)


def camel(s: str) -> str:
    """letters-only CamelCase token for a LaTeX command name."""
    parts = re.split(r"[^A-Za-z]+", s)
    return "".join(p[:1].upper() + p[1:] for p in parts if p)


def main() -> None:
    a = json.loads((C.RESULTS / "analysis.json").read_text())
    M: dict[str, str] = {}

    def put(name: str, val, nd: int = 3) -> None:
        if isinstance(val, float):
            val = f"{val:.{nd}f}"
        M[name] = str(val)

    # sample counts
    put("NCf", a["n_samples"]["cf"], 0)
    put("NLegendary", a["n_samples"]["legendary"], 0)
    put("NAtcoder", a["n_samples"].get("atcoder", 0), 0)
    put("NModels", len(a.get("llm_models", [])), 0)
    mean_delta = sum(a["cell_aurocs"]["delta_confound"][d]["delta"] for d in DET) / len(DET)
    put("MeanDelta", mean_delta)
    mean_hslope = sum(a["within_species_slopes"][d]["human_slope"] for d in DET) / len(DET)
    put("MeanHumanSlope", mean_hslope, 2)

    for det in DET:
        D = camel(det)  # e.g. DroidDetect / FastDetectGpt / Binoculars
        dc = a["cell_aurocs"]["delta_confound"][det]
        put(f"Delta{D}", dc["delta"])
        put(f"AurocMatched{D}", dc["auroc_matched"])
        put(f"AurocMismatched{D}", dc["auroc_mismatched"])
        ci = a["delta_confound_ci"].get(det, {})
        if ci:
            put(f"DeltaCIlo{D}", ci["ci_lo"]); put(f"DeltaCIhi{D}", ci["ci_hi"])
        sl = a["within_species_slopes"][det]
        put(f"HumanSlope{D}", sl["human_slope"], 2)
        put(f"HumanSlopeLo{D}", sl["human_ci"][0], 2); put(f"HumanSlopeHi{D}", sl["human_ci"][1], 2)
        put(f"LlmSlope{D}", sl["llm_slope"], 2)
        put(f"LlmSlopeLo{D}", sl["llm_ci"][0], 2); put(f"LlmSlopeHi{D}", sl["llm_ci"][1], 2)
        put(f"StyleRsq{D}", a["style_mediation"][det]["r2_style"])
        if a.get("legendary"):
            lg = a["legendary"]["by_detector"][det]
            put(f"LegFlag{D}", lg["flag_rate_5pctFPR"])
        if a.get("atcoder_author_skill"):
            at = a["atcoder_author_skill"]["by_detector"][det]
            put(f"AtSlope{D}", at["slope_per_400elo"]); put(f"AtHiLo{D}", at["high_minus_low"], 2)

    # legendary specifics
    if a.get("legendary"):
        put("LegFlagDroidNative", a["legendary"]["by_detector"]["DroidDetect"]["flag_rate_native_0.5"])
        for au, v in a["legendary"]["by_author"].items():
            put(f"LegAuthor{camel(au)}", v["DroidDetect"]["flag_rate_5pctFPR"])
            put(f"LegAuthor{camel(au)}N", v["n"], 0)
        # DroidDetect native-argmax operating point (its actual predictions)
        na = a["legendary"].get("native_argmax_DroidDetect", {})
        if na:
            put("DroidArgmaxCfHumanFPR", na["cf_human"]["flag_rate"])
            put("DroidArgmaxCfLlm", na["cf_llm"]["flag_rate"])
            put("DroidArgmaxLegendary", na["legendary"]["flag_rate"])
            for au, v in na["by_author"].items():
                put(f"DroidArgmax{camel(au)}", v["flag_rate"])

    # atcoder bands
    if a.get("atcoder_author_skill"):
        at = a["atcoder_author_skill"]
        for b, n in at["band_n"].items():
            put(f"AtN{camel(b)}", n, 0)
        for b, r in at["mean_rating"].items():
            put(f"AtRating{camel(b)}", round(r), 0)

    # difficulty -> style (humans), a few key features
    d2s = a["difficulty_to_style"]
    for feat in ["feat_has_type_hints", "feat_comment_density", "feat_mean_identifier_len"]:
        if feat in d2s:
            nm = camel(feat.replace("feat_", ""))
            put(f"Style{nm}Easy", d2s[feat]["easy"]); put(f"Style{nm}Hard", d2s[feat]["hard"])

    # DroidDetect in-distribution validation (proof the implementation is faithful)
    val_path = C.RESULTS / "droiddetect_validation.json"
    if val_path.exists():
        v = json.loads(val_path.read_text())
        put("DroidInDistAUROC", v["auroc_in_distribution"])
        put("DroidInDistHumanFPR", v["human_flag_rate_argmax"])
        put("DroidInDistMachineFlag", v["machine_flag_rate_argmax"])

    lines = [f"\\newcommand{{\\res{k}}}{{{v}}}" for k, v in sorted(M.items())]
    header = ("% AUTO-GENERATED by scripts/06_build_macros.py from results/analysis.json.\n"
              "% Variables only. Do NOT edit by hand and do NOT type numbers into paper.tex —\n"
              "% reference these macros (\\res...) instead. Re-run the pipeline to refresh.\n")
    (PAPER / "macros.tex").write_text(header + "\n".join(lines) + "\n")
    print(f"wrote paper/macros.tex ({len(M)} macros)")


if __name__ == "__main__":
    main()
